apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingapp-deploy
  labels:
    app: banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: bankingapp-container
        image: madhavan2454/project-bankingapp-img:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankingapp-nodeport-service
  labels:
    app: banking-app
spec:
  selector:
    app: banking-app

  type: NodePort
  ports:
  - nodePort: 31031  
    port: 8081
    targetPort: 8081
